// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.1
// source: flashsale.proto

package flashsale

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GeneralReq) Reset() {
	*x = GeneralReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flashsale_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralReq) ProtoMessage() {}

func (x *GeneralReq) ProtoReflect() protoreflect.Message {
	mi := &file_flashsale_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralReq.ProtoReflect.Descriptor instead.
func (*GeneralReq) Descriptor() ([]byte, []int) {
	return file_flashsale_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GeneralResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GeneralResp) Reset() {
	*x = GeneralResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flashsale_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResp) ProtoMessage() {}

func (x *GeneralResp) ProtoReflect() protoreflect.Message {
	mi := &file_flashsale_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResp.ProtoReflect.Descriptor instead.
func (*GeneralResp) Descriptor() ([]byte, []int) {
	return file_flashsale_proto_rawDescGZIP(), []int{1}
}

func (x *GeneralResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GeneralResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FlashsaleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *FlashsaleReq) Reset() {
	*x = FlashsaleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flashsale_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashsaleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashsaleReq) ProtoMessage() {}

func (x *FlashsaleReq) ProtoReflect() protoreflect.Message {
	mi := &file_flashsale_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashsaleReq.ProtoReflect.Descriptor instead.
func (*FlashsaleReq) Descriptor() ([]byte, []int) {
	return file_flashsale_proto_rawDescGZIP(), []int{2}
}

func (x *FlashsaleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlashsaleReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_flashsale_proto protoreflect.FileDescriptor

var file_flashsale_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x22, 0x1c, 0x0a, 0x0a,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0b, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x34, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x32, 0x55, 0x0a, 0x10, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x66, 0x6c,
	0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x73, 0x61, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_flashsale_proto_rawDescOnce sync.Once
	file_flashsale_proto_rawDescData = file_flashsale_proto_rawDesc
)

func file_flashsale_proto_rawDescGZIP() []byte {
	file_flashsale_proto_rawDescOnce.Do(func() {
		file_flashsale_proto_rawDescData = protoimpl.X.CompressGZIP(file_flashsale_proto_rawDescData)
	})
	return file_flashsale_proto_rawDescData
}

var file_flashsale_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flashsale_proto_goTypes = []interface{}{
	(*GeneralReq)(nil),   // 0: flashsale.GeneralReq
	(*GeneralResp)(nil),  // 1: flashsale.GeneralResp
	(*FlashsaleReq)(nil), // 2: flashsale.FlashsaleReq
}
var file_flashsale_proto_depIdxs = []int32{
	2, // 0: flashsale.FlashsaleService.FrontFlashsale:input_type -> flashsale.FlashsaleReq
	1, // 1: flashsale.FlashsaleService.FrontFlashsale:output_type -> flashsale.GeneralResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flashsale_proto_init() }
func file_flashsale_proto_init() {
	if File_flashsale_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flashsale_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flashsale_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flashsale_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashsaleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flashsale_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flashsale_proto_goTypes,
		DependencyIndexes: file_flashsale_proto_depIdxs,
		MessageInfos:      file_flashsale_proto_msgTypes,
	}.Build()
	File_flashsale_proto = out.File
	file_flashsale_proto_rawDesc = nil
	file_flashsale_proto_goTypes = nil
	file_flashsale_proto_depIdxs = nil
}
