// Code generated by goctl. DO NOT EDIT.
// Source: flashsale.proto

package server

import (
	"context"

	"pan-blitz-buy/rpc/flashsale/flashsale"
	"pan-blitz-buy/rpc/flashsale/internal/logic"
	"pan-blitz-buy/rpc/flashsale/internal/svc"
)

type FlashsaleServiceServer struct {
	svcCtx *svc.ServiceContext
	flashsale.UnimplementedFlashsaleServiceServer
}

func NewFlashsaleServiceServer(svcCtx *svc.ServiceContext) *FlashsaleServiceServer {
	return &FlashsaleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FlashsaleServiceServer) FrontFlashsale(ctx context.Context, in *flashsale.FlashsaleReq) (*flashsale.GeneralResp, error) {
	l := logic.NewFrontFlashsaleLogic(ctx, s.svcCtx)
	return l.FrontFlashsale(in)
}
